---

- hosts: logger
  roles:
    - logger
  tags: logger

- hosts: dc1
  roles:
    - dc1
    - monitor
  tags: dc1

- hosts: workstation1
  roles:
    - workstation1
    - common
    - monitor
  tags: workstation1

- hosts: workstation2
  roles:
    - workstation2
    - common
    - monitor
  tags: workstation2
